language: clojure
jdk:
  - openjdk8
  - openjdk11
deploy:
  skip_cleanup: true
  provider: script
  script: lein deploy
  on:
    tags: true
    jdk: openjdk8
env:
  global:
  - secure: cvdYdw/l7jT0oDNdrb1kX/iSYaCuKF+gaBfnjLM9eOqEAoTQZ+Z1uBxRXzEpkK7sP54pCkOPm/9Fcl1abEZiI9nbhmkvb5KZx8PYClr29gCkl00xB7moclcIrb8GULrrn9Ju5J5DBHF8cSntDFo+XukQmtzmWoya9UarwKab8Ku8lWhTq8kM1L6PAWej1ZLXbqe2OpEgIm77DUFRCLykSGa6RAi4WbUz40ERcie+cyK6ocGGfs+T4w8tsZhzaSRMAgtZU0C/5HY7FCI9sSS+pZykg+wlfH6IInEIe92rsm/1inOlOYIPsZQUJ0qNF/FGtIAQwGoXFsAoyE0LEUjoMAwstD28I7vw+5+v8tmlfKK5Sh0+oA5dxyAltl2B6rttqUCK0ddabpnHr3y6cVSICEAY71MIaA/0D1p5dBqihlD/MJKq/Fd0Ymz1xT1IcbcKRriZ7FnuzsM8JcsFNPR/QzkqSsFu+8jF/0p+bkDZKiPzvOXm0PASPmMD45GRpUhtA0kCl0Adh71nAudiKFDTbmHJ/E7CsURZ6UEYMlGfYaFmi9OeyCHhNGeNsXgI/lXlO834KIdQ+bOgpxS5jqZEdm7h4t5z5GWxfhqr68UD685Tw5SwCxvRUviIfbXxhq87quNiRbu7qxWFxqn6ohAMAPbzV0bNXvkFxoJ/ioLO2mw=
  - secure: exR3subuKv9UoAipGN9TVugIvnsklMIdEOlqvhIIr0ucvBWbukVrFqKuDuHHe9e1r0nfRvGVGk43CXc/1mLPmxPWaZYEUkK9BWMsrci3qF+akUk/4TQlibnHDRYVNoBI3FQD8A55/FphMavmGYOhPp5c80OvJVUiKLzJ0pqy9o2ioVYaxC79aOh2ABN24O5xW6wOnYC3Der2nnke8Jk6aTa2JX6lEnEeNOj2AU2RqucatKK+v8Dj9FCo5eW1INu+Gzmpn5WdJprhzufUJcfBT2UzKTh5iuAtx2D/amcsB4+7/ceX2i3RaG+I60zO5EwUN9vwYWfsi645w72CqXxo9HdVBwXLBkEYBDBnVNZTmCBtNMjYBfhSDSijCIhnpHPQ5wt2B1ZZV8F6+Io9bHy+cwaO3k/w4mY6oDSJf1IdYgzRX+bfEdenBv5Nbha88DVaNjyvePXNrj6USHIOEfN4NqqLe/y7UNAe1pNo2YRVJJAslrpukmaePVVcONdhNqzrxm3d4RtGqTApWgj+xCGBSAZ4ELY9fefCSbQOxob5c0mKV2K7ABhnRbve3tA4bW5K3AtJp4jg+be7/Ia2p/EtYh298sSOXE8sbzfktkbYO6vB8L4bPZAPJIMgBG4hts28kIkDy18z9dcENrAr3IcN6AVh6LUzYhBqOLyQV/Oy8Ac=
